"""Convert a VIA-format Hufnagel CSV + page image into a GameraXML training file.

The Hufnagel annotation CSV (e.g. ``fixtures/Hufnagel-example.csv``) is a
VIA export: one bbox per row plus a free-form ``type`` label. We crop each
bbox out of the companion page image, binarise, and write the result as a
GameraXML database matching the schema of
``fixtures/Interactive_Classifier_GameraXML_TrainingData.xml`` — so the
new glyphs can be loaded by :func:`ic_core.io_xml.load_glyphs` and used as
KNN training data.

Class labels in the Hufnagel CSV (``f-clef``, ``puncta``, ``pes``, …)
don't all line up with the existing GameraXML vocabulary. The
:data:`HUFNAGEL_TO_GAMERA` table translates the recognised ones and passes
the rest through verbatim — edit it as mapping decisions are made.

Run::

    cd core/ic_core && uv run python ../tests/sample_input/helpers/convert_hufnagel_csv.py
"""
from __future__ import annotations

import argparse
import csv
import json
import uuid
from collections import Counter
from dataclasses import replace
from pathlib import Path

from ic_core.glyph import Glyph
from ic_core.ingest import ingest_page
from ic_core.io_xml import write_glyphs

HERE = Path(__file__).parent
SAMPLE_DIR = HERE.parent
FIXTURES = SAMPLE_DIR.parent / "fixtures"

DEFAULT_CSV = FIXTURES / "Hufnagel-example.csv"
DEFAULT_PAGE = SAMPLE_DIR / "Hufnagel-example.png"
DEFAULT_OUTPUT_XML = FIXTURES / "Hufnagel-example_training_data.xml"
#: MOTHRA-shaped JSON sidecar for visualize.py / ingest_page_json
#: consumers. Lives next to the page image so it's picked up by
#: relative paths like SAMPLE_DIR / "Hufnagel-example_annotations.json".
DEFAULT_OUTPUT_JSON = SAMPLE_DIR / "Hufnagel-example_annotations.json"

#: Map Hufnagel CSV ``type`` strings to GameraXML vocabulary. Entries
#: where the value equals the key are pass-throughs — they emit the raw
#: Hufnagel label and need a real mapping decision. Edit in place.
HUFNAGEL_TO_GAMERA: dict[str, str] = {
    "f-clef": "clef.f",
    "custos": "custos",
    "puncta": "neume.punctum",
    "torculus": "neume.torculus2",
    "virga": "neume.virga",
    "pes": "neume.pescephalicus2",
    "clivis": "neume.clivis2",
    "scandicus": "neume.scandicus22a",
    "divisio": "divisio.maxima",
}


def parse_via_csv(csv_path: Path) -> list[tuple[int, int, int, int, str]]:
    """Return ``(x, y, w, h, raw_class)`` tuples in CSV row order.

    Non-rect shapes are skipped. The CSV's ``filename`` column is
    informational — we don't dispatch on it, so a multi-file CSV
    silently merges into one output file. Callers wanting per-file
    output should filter first.
    """
    rows: list[tuple[int, int, int, int, str]] = []
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            shape = json.loads(row["region_shape_attributes"])
            attrs = json.loads(row["region_attributes"])
            if shape.get("name") != "rect":
                continue
            raw_class = (attrs.get("type") or "").strip()
            if not raw_class:
                continue
            rows.append(
                (
                    int(shape["x"]),
                    int(shape["y"]),
                    int(shape["width"]),
                    int(shape["height"]),
                    raw_class,
                )
            )
    return rows


def _stable_ids(csv_path: Path, count: int) -> list[str]:
    """Derive stable per-row UUIDs from the CSV filename + row index.

    Using uuid5 (deterministic) means re-running the converter doesn't
    churn the JSON's ids — the sidecar diff stays clean unless the
    underlying CSV actually changes.
    """
    namespace = uuid.uuid5(uuid.NAMESPACE_URL, csv_path.name)
    return [str(uuid.uuid5(namespace, str(i))) for i in range(count)]


def convert(
    csv_path: Path = DEFAULT_CSV,
    page_path: Path = DEFAULT_PAGE,
    output_xml: Path = DEFAULT_OUTPUT_XML,
    output_json: Path | None = DEFAULT_OUTPUT_JSON,
) -> list[Glyph]:
    """Crop the Hufnagel page using the CSV bboxes and write GameraXML.

    Returns the glyphs in CSV order. Each glyph is marked
    ``id_state_manual=True`` and ``confidence=1.0`` so it serialises
    as ``state="MANUAL"`` — matching the legacy training database.

    Also writes a MOTHRA-shaped JSON sidecar (unless ``output_json``
    is ``None``) so ``visualize.py`` and ``ingest_page_json`` can read
    the same bboxes without re-parsing the CSV. The training XML and
    the JSON share the per-row uuid5 ids generated by
    :func:`_stable_ids`, so glyphs ingested from the JSON line up
    one-to-one with the training XML by id.
    """
    annotations = parse_via_csv(csv_path)
    ids = _stable_ids(csv_path, len(annotations))

    # Hand the bboxes to ingest_page so cropping + binarisation + RLE
    # encoding use the exact same code path as live ingest. We
    # synthesise the MOTHRA JSON shape it expects.
    doc = {
        "annotations": [
            {"id": gid, "bbox": [x, y, w, h]}
            for gid, (x, y, w, h, _) in zip(ids, annotations)
        ],
    }
    glyphs = ingest_page(
        page_path.read_bytes(),
        json.dumps(doc).encode("utf-8"),
        format="json",
    )

    training: list[Glyph] = []
    for g, (_, _, _, _, raw_class) in zip(glyphs, annotations):
        mapped = HUFNAGEL_TO_GAMERA.get(raw_class, raw_class)
        training.append(
            replace(
                g,
                class_name=mapped,
                confidence=1.0,
                id_state_manual=True,
                is_training=True,
            )
        )

    write_glyphs(training, output_xml)

    if output_json is not None:
        sidecar = {
            "imageName": page_path.name,
            "annotations": [
                {
                    "id": gid,
                    "classId": 2,
                    "bbox": [x, y, w, h],
                    "type": raw_class,
                }
                for gid, (x, y, w, h, raw_class) in zip(ids, annotations)
            ],
        }
        output_json.write_text(json.dumps(sidecar, indent=2))

    return training


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    parser.add_argument("--page", type=Path, default=DEFAULT_PAGE)
    parser.add_argument("--out-xml", type=Path, default=DEFAULT_OUTPUT_XML)
    parser.add_argument("--out-json", type=Path, default=DEFAULT_OUTPUT_JSON)
    args = parser.parse_args()

    glyphs = convert(args.csv, args.page, args.out_xml, args.out_json)
    print(f"Wrote {len(glyphs)} glyphs to {args.out_xml}")
    print(f"Wrote {len(glyphs)} annotations to {args.out_json}")

    # A class is "pass-through" iff its raw CSV label wasn't really
    # translated — either absent from the mapping, or present with
    # value == key. Re-read the raw labels rather than infer from
    # the (already mapped) glyph.class_name.
    raw_classes = [raw for *_, raw in parse_via_csv(args.csv)]
    pass_through_mapped = {
        HUFNAGEL_TO_GAMERA.get(r, r)
        for r in raw_classes
        if HUFNAGEL_TO_GAMERA.get(r, r) == r
    }
    counts = Counter(g.class_name for g in glyphs)
    print("Class histogram:")
    for name, n in counts.most_common():
        flag = "  (pass-through, needs mapping)" if name in pass_through_mapped else ""
        print(f"  {n:4d}  {name}{flag}")


if __name__ == "__main__":
    main()
